[package]
name = "arraystring"
version = "0.4.0"
repository = "https://github.com/paulocsanz/arraystring"
description = "Fixed capacity stack based generic string"
authors = ["Paulo Cabral Sanz <paulosanz@poli.ufrj.br>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["string", "generic", "array", "stack", "no_std"]
categories = ["data-structures"]
edition = "2021"

[lib]
name = "arraystring"
crate_type = ["lib"]

[[bench]]
name = "string"
harness = false

[dev-dependencies]
inlinable_string = "0.1"
smallstring = "0.1"
arrayvec = "0.7"
serde_json = "1.0"
criterion = { version = "0.4", features = ["html_reports"] }
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2", features = ["sqlite", "postgres", "mysql"] }

[dependencies]
log = { version = "0.4", optional = true }
serde = { version = "1", optional = true }
diesel = { version = "2", optional = true }
no-panic = { version = "0.1", optional = true }

[features]
default = ["std"]
std = []
logs = ["log"]
serde-traits = ["serde"]
diesel-traits = ["diesel"]
no-panic = ["dep:no-panic"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs_workaraound"]
features = ["logs", "serde-traits", "std", "diesel-traits", "no-panic"]
